// This file is generated by scripts/files.dart
// Do not edit this file directly
//
const files = {
  "apps": [
    {
      "name": "the-pocket-piano",
      "title": "The Pocket Piano",
      "date": "2018-06-08",
      "tags": ["music", "piano", "ios", "android"],
      "image": "/img/the-pocket-piano/icon.png"
    },
    {
      "name": "hymns-for-worship",
      "title": "Hymns for Worship",
      "date": "2019-01-01",
      "tags": [
        "pitch pipe",
        "music",
        "teachers",
        "education",
        "ios",
        "android"
      ],
      "image": "/assets/images/hymns-for-worship_icon.png"
    },
    {
      "name": "widget-studio",
      "title": "Widget Studio",
      "date": "2018-06-08",
      "tags": [
        "ide",
        "editor",
        "code",
        "drag-and-drop",
        "flutter",
        "ios",
        "android",
        "desktop"
      ],
      "image": "/img/widget-studio/icon.png"
    },
    {
      "name": "the-pitch-pipe",
      "title": "The Pitch Pipe",
      "date": "2017-03-10",
      "tags": [
        "pitch pipe",
        "music",
        "teachers",
        "education",
        "ios",
        "android"
      ],
      "image": "/img/the-pitch-pipe/icon.png"
    },
    {
      "name": "space-curiosity",
      "title": "Launching... Space Curiosity",
      "date": "2019-03-10",
      "tags": [
        "flutter",
        "spacex",
        "nasa",
        "iss",
        "planets",
        "space",
        "ios",
        "android"
      ],
      "image": "/assets/images/space-curiosity_icon.png"
    }
  ],
  "posts": [
    {
      "name": "making-a-piano",
      "title": "Building A Piano with Flutter",
      "date": "2019-03-12",
      "publishDate": "12 Mar 2019",
      "tags": ["posts", "flutter", "music"],
      "image": "/assets/images/flutter_piano_final.png"
    },
    {
      "name": "lit-sheet-music",
      "title": "Lit Sheet Music",
      "date": "2021-06-04",
      "publishDate": "4 Jun 2021",
      "tags": ["posts", "web", "lit", "sheet-music", "music", "html", "vite"]
    },
    {
      "name": "lit-force-graph",
      "title": "2D/3D Force Graph with Lit",
      "date": "2022-07-04",
      "publishDate": "7 Apr 2022",
      "tags": [],
      "image": "/img/lit/force-graph/3d-dark.png"
    },
    {
      "name": "flutter-and-lit",
      "title": "Lit and Flutter",
      "date": "2021-05-05",
      "publishDate": "5 May 2021",
      "tags": ["posts", "flutter", "web", "vite", "lit"],
      "image": "/img/flutter/first.png"
    },
    {
      "name": "codemirror-dynamic-theme",
      "title": "Dynamic Themes with CodeMirror",
      "date": "2022-03-17",
      "publishDate": "17 Mar 2022",
      "tags": [],
      "image": "/img/dynamic-theme/purple-dark.png"
    },
    {
      "name": "flutter-one-click-release",
      "title": "Flutter + Fastlane (One Click Beta)",
      "date": "2019-03-11",
      "publishDate": "11 Mar 2019",
      "tags": ["posts", "flutter", "ci", "scripting"],
      "image": "/img/flutter/first.png"
    },
    {
      "name": "figma-and-lit",
      "title": "Lit and Figma",
      "date": "2021-05-10",
      "publishDate": "10 May 2021",
      "tags": ["posts", "lit", "figma", "plugin", "webpack", "web"],
      "image": "/img/figma/rectangles.png"
    },
    {
      "name": "static-site-file-based-routing",
      "title": "File Based Routing for Static Sites",
      "date": "2022-09-28",
      "publishDate": "28 Sep 2022",
      "tags": [
        "posts",
        "static-site",
        "file-based-routing",
        "multi-page-application",
        "web",
        "css"
      ],
      "image": "/img/static-site/preview.png"
    },
    {
      "name": "flutter-cheat-sheet",
      "title": "Flutter Cheat Sheet — Terminal",
      "date": "2020-03-05",
      "publishDate": "5 Mar 2020",
      "tags": ["posts", "flutter", "scripting"],
      "image": "/img/flutter/first.png"
    },
    {
      "name": "automate-flutter-apps",
      "title": "Automate Flutter App Releases",
      "date": "2019-03-15",
      "publishDate": "15 Mar 2019",
      "tags": ["posts", "flutter", "apps", "ci"],
      "image": "/img/flutter/fastlane.jpg"
    },
    {
      "name": "podcast-github-pages",
      "title": "How To Host Your Podcast For Free On Github Pages",
      "date": "2020-03-27",
      "publishDate": "27 Mar 2020",
      "tags": ["posts", "flutter", "podcast", "github"],
      "image": "/img/podcast-github/gh-pages.jpeg"
    },
    {
      "name": "pocketbase-cloudrun",
      "title": "How to deploy PocketBase to Cloud Run",
      "date": "2022-09-24",
      "publishDate": "24 Sep 2022",
      "tags": ["posts", "sqlite"],
      "image": "/img/pocketbase/thumbnail.png"
    },
    {
      "name": "fastlane-and-flutter",
      "title": "Using Fastlane in Flutter and CI",
      "date": "2019-10-16",
      "publishDate": "16 Oct 2019",
      "tags": ["posts", "flutter", "ci", "ci"],
      "image": "/img/flutter/fastlane.jpg"
    },
    {
      "name": "html-code-sandbox",
      "title": "Building a HTML Element Sandbox with Lit",
      "date": "2022-05-24",
      "publishDate": "24 May 2022",
      "tags": [],
      "image": "/img/html-sandbox/preview.png"
    },
    {
      "name": "lit-vscode-extension",
      "title": "Lit and VSCode Extensions",
      "date": "2021-06-24",
      "publishDate": "24 Jun 2021",
      "tags": ["posts", "vscode", "web", "lit", "plugin", "vite", "extension"],
      "image": "/img/vscode/final.png"
    },
    {
      "name": "lit-monaco-editor",
      "title": "Lit and Monaco Editor",
      "date": "2021-07-29",
      "publishDate": "29 Jul 2021",
      "tags": ["posts", "lit", "vscode", "editor", "web", "vite"],
      "image": "/img/code-editor/dark.png"
    },
    {
      "name": "lit-rich-text-editor",
      "title": "Building a Rich Text Editor with Lit",
      "date": "2021-05-26",
      "publishDate": "26 May 2021",
      "tags": [
        "posts",
        "editor",
        "web",
        "lit",
        "wysiwyg",
        "vite",
        "playground"
      ],
      "image": "/img/rich-text/editor-finish.png"
    },
    {
      "name": "flutter-master-detail",
      "title": "Building a Master / Detail list with Flutter",
      "date": "2022-04-17",
      "publishDate": "17 Apr 2022",
      "tags": ["posts", "flutter", "layout", "design", "ui"],
      "image": "/img/flutter/first.png"
    },
    {
      "name": "push-notifications-flutter-web",
      "title": "How To Send Push Notifications on Flutter Web (FCM)",
      "date": "2020-05-01",
      "publishDate": "01 May 2020",
      "tags": ["posts", "flutter", "web"],
      "image": "/img/firebase/banner.png"
    },
    {
      "name": "lit-html-table",
      "title": "JSON to HTML Table with Lit",
      "date": "2021-06-03",
      "publishDate": "3 Jun 2021",
      "tags": [],
      "image": "/img/json-to-table/finished.png"
    },
    {
      "name": "host-flutter-rest-api",
      "title": "Host your Flutter Project as a REST API",
      "date": "2019-10-18",
      "publishDate": "18 Oct 2019",
      "tags": ["posts", "flutter", "api"]
    },
    {
      "name": "first-flutter-project",
      "title": "Creating Your First Flutter Project",
      "date": "2019-04-28",
      "publishDate": "28 Apr 2019",
      "tags": ["posts", "flutter"],
      "image": "/img/flutter/first.png"
    },
    {
      "name": "deep-linking-flutter-web",
      "title": "Deep Linking for Flutter Web",
      "date": "2020-03-11",
      "publishDate": "11 Mar 2020",
      "tags": ["posts", "flutter", "web"],
      "image": "/img/deep-linking/0.png"
    },
    {
      "name": "lit-draggable-dom",
      "title": "Draggable DOM with Lit",
      "date": "2021-06-23",
      "publishDate": "23 Jun 2021",
      "tags": ["posts", "web", "lit", "css", "canvas", "vite", "playground"],
      "image": "/img/draggable-dom/canvas.png"
    },
    {
      "name": "flutter-and-xcode-cloud",
      "title": "How to build a Flutter app on Xcode Cloud",
      "date": "2022-06-05",
      "publishDate": "6 Jun 2022",
      "tags": [],
      "image": "/img/flutter/xcode-cloud.png"
    },
    {
      "name": "native-cross-platform-flutter",
      "title": "How to build a native cross platform project with Flutter",
      "date": "2019-09-06",
      "publishDate": "6 Sep 2019",
      "tags": ["posts", "flutter"],
      "image": "/img/flutter/first.png"
    },
    {
      "name": "display-html-in-flutter",
      "title": "Displaying HTML in Flutter",
      "date": "2020-03-10",
      "publishDate": "10 Mar 2020",
      "tags": ["posts", "flutter", "web"]
    },
    {
      "name": "flutter-multi-touch-canvas",
      "title": "Multi-touch Canvas with Flutter",
      "date": "2020-06-10",
      "publishDate": "10 Jun 2020",
      "tags": ["posts", "flutter", "graphics"],
      "image": "/img/flutter/multi-touch.png"
    }
  ],
  "static": [
    {"name": "privacy", "title": "Privacy Policy"},
    {"name": "talks", "title": "Talks"},
    {"name": "about", "title": "About"}
  ]
};
