site:
  title: "Rody Davis"
  description: "Personal website for Rody Davis"
  url: https://rodydavis.com
  copyright_name: Rody Davis
social:
  github:
    username: "rodydavis"
  twitter:
    username: "rodydavis"
  facebook:
    username: "rodydavisjr"
  instagram:
    username: "rodydavisjr"
  youtube:
    username: "rodydavis"
  tiktok:
    username: "rodydavisjr"
  linkedin:
    username: "rodydavis"
menu:
  apps:
    label: Apps
    link: /search?tags=app
  blog:
    label: Blog
    link: /search?tags=posts
  talks:
    label: Talks
    link: /talks
  about:
    label: About
    link: /about
  search:
    label: Search
    link: /search
