version: "3.8"
services:
  pocketbase:
    image: registry.rodydavis.dev/website:latest
    volumes:
      - ./pb_data:/app/pb_data
    ports:
      - target: 8090
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
        failure_action: rollback
      placement:
        constraints:
          - node.labels.storage == shared
