name: rodydavis
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0-77.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^6.0.1
  recase: ^4.1.0
  flutter_markdown: ^0.6.13
  url_launcher: ^6.1.8
  flutter_riverpod: ^2.1.3
  flutter_staggered_grid_view: ^0.6.2
  collection: ^1.17.0
  flutter_svg: ^1.1.6
  markdown: ^6.0.1
  flutter_highlighter: ^0.1.1
  google_fonts: ^3.0.1
  shared_preferences: ^2.0.17
  seo: ^0.0.4
  reading_time: ^2.0.0
  rss_generator: ^1.0.0
  firebase_core: ^2.4.1
  firebase_analytics: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/data/apps/
    - assets/data/blog/
    - assets/data/static/
    - assets/images/
    - assets/images/social/

scripts:
  build:
    - dart scripts/files.dart
    - dart scripts/rss.dart
    - flutter build web --web-renderer=html