import 'dart:convert';
import 'dart:io';

import 'info.dart';

final inDir = Directory('./assets/data');
final outFile = File('./lib/data/source/files/files.g.dart');

void main() {
  final out = <String, List<Object>>{};
  final apps = Directory('${inDir.path}/apps').listSync().whereType<File>();
  out['apps'] = [];
  for (final app in apps) {
    out['apps']!.add(getInfo(app));
  }
  final posts = Directory('${inDir.path}/blog').listSync().whereType<File>();
  out['posts'] = [];
  for (final post in posts) {
    out['posts']!.add(getInfo(post));
  }
  final extra = Directory('${inDir.path}/static').listSync().whereType<File>();
  out['static'] = [];
  for (final file in extra) {
    out['static']!.add(getInfo(file));
  }
  final result = jsonEncode(out);
  if (!outFile.existsSync()) outFile.createSync(recursive: true);
  final sb = StringBuffer();
  sb.writeln('// This file is generated by scripts/files.dart');
  sb.writeln('// Do not edit this file directly');
  sb.writeln('//');
  sb.writeln('const files = $result;');
  sb.writeln();
  outFile.writeAsStringSync(sb.toString());
}
