import 'dart:convert';
import 'dart:io';

final inDir = Directory('./assets/data');
final outFile = File('./lib/data/source/files/files.g.dart');

void main() {
  final out = <String, List<Object>>{};
  final apps = Directory('${inDir.path}/apps').listSync().whereType<File>();
  out['apps'] = [];
  for (final app in apps) {
    out['apps']!.add(getInfo(app));
  }
  final posts = Directory('${inDir.path}/blog').listSync().whereType<File>();
  out['posts'] = [];
  for (final post in posts) {
    out['posts']!.add(getInfo(post));
  }
  final result = jsonEncode(out);
  if (!outFile.existsSync()) outFile.createSync(recursive: true);
  final sb = StringBuffer();
  sb.writeln('// This file is generated by scripts/files.dart');
  sb.writeln('// Do not edit this file directly');
  sb.writeln('//');
  sb.writeln('const files = $result;');
  sb.writeln();
  outFile.writeAsStringSync(sb.toString());
}

Map<String, dynamic> getInfo(File file) {
// ---
// title: "Automate Flutter App Releases"
// date: 2019-03-15
// publishDate: 15 Mar 2019
// tags:
// - posts
// - flutter
// - apps
// - ci
// image: /img/flutter/fastlane.jpg
// ---
  final name = file.path.split('/').last.split('.').first;
  final contents = file.readAsStringSync();
  final output = <String, dynamic>{};
  output['name'] = name;
  String frontMatter = '';
  if (contents.startsWith('---') && contents.contains('---', 3)) {
    frontMatter = contents.substring(3, contents.indexOf('---', 3));
  }
  if (frontMatter.isNotEmpty) {
    final lines = frontMatter.split('\n');
    for (final line in lines) {
      final parts = line.split(':');
      if (parts.length == 2) {
        final key = parts[0].trim();
        final value = parts[1].trim();
        if (key == 'title') {
          output['title'] = removeQuotes(value);
        } else if (key == 'date') {
          output['date'] = value;
        } else if (key == 'publishDate') {
          output['publishDate'] = value;
        } else if (key == 'tags') {
          // Get tag list
          final lines = frontMatter.split('\n');
          final tags = <String>[];
          final startIdx = lines.indexOf('tags:');
          for (var i = startIdx + 1; i < lines.length; i++) {
            final line = lines[i];
            if (line.startsWith('-')) {
              tags.add(line.substring(2).trim());
            } else {
              break;
            }
          }
          output['tags'] = tags;
        } else if (key == 'image') {
          output['image'] = value;
        }
      }
    }
  }
  return output;
}

String removeQuotes(String value) {
  if (value.startsWith('"') && value.endsWith('"')) {
    return value.substring(1, value.length - 1);
  }
  return value;
}
