# This workflow builds a Docker image and pushes it to Docker Hub
# when a new Git tag is pushed.

name: Build and Push Docker Image to Docker Hub

on:
  # Trigger the workflow when a push occurs on the 'main' branch
  push:
    branches:
      - master
      - main

env:
  DOCKER_HUB_USERNAME: rodydavis
  DOCKER_HUB_REPO: rodydavis

jobs:
  build_and_push:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Checkout repository
        # Action to check out your repository code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        # Action to log in to Docker Hub using provided credentials
        # DOCKER_USERNAME and DOCKER_PASSWORD should be stored as GitHub Secrets
        # Go to your repository settings -> Secrets and variables -> Actions
        # Add new repository secrets: DOCKER_USERNAME and DOCKER_PASSWORD
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        # Action to set up Docker Buildx, which provides enhanced build capabilities
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        # This step builds the Docker image and pushes it to Docker Hub.
        # It will only push the image with the 'latest' tag.
        uses: docker/build-push-action@v5
        with:
          context: . # Build context is the current directory
          push: true # Push the image to the registry
          tags: ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_HUB_REPO }}:latest
